services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - quoteboard
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
  quoteboard:
    build: .
    expose:
      - "8000"
    restart: always
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      STATIC_URL: /static/
      STATIC_ROOT: /app/static
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quoteboard
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - static:/app/static
      - media:/app/media
  postgres:
    image: postgres:latest
    container_name: quoteboard_db
    environment:
      POSTGRES_DB: quoteboard
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data:
  static:
  media: